import assert from 'assert'; import bcrypt from 'bcryptjs'; import http from 'http'; import mongoose from 'mongoose'; import axios from 'axios';
import app from '../../server'; import User from '../models/User'; import OtpVerification from '../models/OtpVerification'; import { otpDeliveryService } from '../services/otp-delivery.service'; import { rateLimiterStore } from '../middleware/rate-limiter';
const PORT=5126,base=`http://127.0.0.1:${PORT}`,uri=process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/sih_demo';let server:http.Server;
async function main(){await mongoose.connect(uri);server=app.listen(PORT);const checks:string[]=[];const check=async(name:string,fn:()=>Promise<void>)=>{await fn();checks.push(name);console.log(`  ✓ ${name}`)};const stamp=Date.now(),email=`otp.registration.${stamp}@test.com`,email2=`otp.attempts.${stamp}@test.com`,password='Password123!';
try{console.log('Starting Registration OTP and Direct Login Self-Check...\n');
await check('Registration creates an unverified account and requires OTP',async()=>{const r=await axios.post(`${base}/api/auth/register`,{name:'Registration Test Citizen',email,password});assert.equal(r.status,201);assert.equal(r.data.requiresOtp,true);assert.equal(r.data.token,undefined);assert.equal(r.data.user.isVerified,false)});
await check('Registration OTP is six digits and stored only as a bcrypt hash',async()=>{const plain=otpDeliveryService.getDevLatestOtp(email,'REGISTER')!;assert.match(plain,/^\d{6}$/);const record=await OtpVerification.findOne({email,purpose:'REGISTER',consumed:false});assert.ok(record);assert.notEqual(record!.otpHash,plain);assert.ok(await bcrypt.compare(plain,record!.otpHash))});
await check('Unverified account cannot log in',async()=>{const r=await axios.post(`${base}/api/auth/login`,{email,password},{validateStatus:()=>true});assert.equal(r.status,403);assert.equal(r.data.requiresVerification,true)});
await check('Invalid registration OTP increments attempts',async()=>{const r=await axios.post(`${base}/api/auth/register/verify-otp`,{email,otp:'000000'},{validateStatus:()=>true});assert.equal(r.status,400);assert.equal((await OtpVerification.findOne({email,purpose:'REGISTER',consumed:false}))?.attempts,1)});
const registrationOtp=otpDeliveryService.getDevLatestOtp(email,'REGISTER')!;
await check('Valid registration OTP verifies the account exactly once',async()=>{const r=await axios.post(`${base}/api/auth/register/verify-otp`,{email,otp:registrationOtp});assert.equal(r.data.user.isVerified,true);const reused=await axios.post(`${base}/api/auth/register/verify-otp`,{email,otp:registrationOtp},{validateStatus:()=>true});assert.equal(reused.status,400)});
await check('Valid email and password return JWT directly without login OTP',async()=>{await OtpVerification.deleteMany({email,purpose:'LOGIN'});const r=await axios.post(`${base}/api/auth/login`,{email,password});assert.equal(r.status,200);assert.equal(r.data.requiresOtp,false);assert.ok(r.data.token);assert.equal(r.data.user.email,email);assert.equal(await OtpVerification.countDocuments({email,purpose:'LOGIN'}),0);assert.equal(otpDeliveryService.getDevLatestOtp(email,'LOGIN'),undefined)});
await check('Invalid password is rejected without JWT or OTP',async()=>{const r=await axios.post(`${base}/api/auth/login`,{email,password:'WrongPassword!'},{validateStatus:()=>true});assert.equal(r.status,401);assert.equal(r.data.token,undefined);assert.equal(await OtpVerification.countDocuments({email,purpose:'LOGIN'}),0)});
await check('Legacy login OTP endpoints cannot authenticate or send OTP',async()=>{const verify=await axios.post(`${base}/api/auth/login/verify-otp`,{email,otp:registrationOtp},{validateStatus:()=>true});const resend=await axios.post(`${base}/api/auth/login/resend-otp`,{email},{validateStatus:()=>true});assert.equal(verify.status,410);assert.equal(resend.status,410);assert.equal(await OtpVerification.countDocuments({email,purpose:'LOGIN'}),0)});
await check('Expired registration OTP is rejected',async()=>{await axios.post(`${base}/api/auth/register`,{name:'Expiry Test Citizen',email:email2,password});await OtpVerification.updateOne({email:email2,purpose:'REGISTER',consumed:false},{$set:{expiresAt:new Date(Date.now()-1000)}});const r=await axios.post(`${base}/api/auth/register/verify-otp`,{email:email2,otp:otpDeliveryService.getDevLatestOtp(email2,'REGISTER')},{validateStatus:()=>true});assert.equal(r.status,400)});
await check('Registration resend invalidates the previous OTP and supplies a single-use replacement',async()=>{const old=await OtpVerification.findOne({email:email2,purpose:'REGISTER',consumed:false});const r=await axios.post(`${base}/api/auth/register/resend-otp`,{email:email2});assert.equal(r.status,200);if(old)assert.equal((await OtpVerification.findById(old._id))?.consumed,true);const fresh=otpDeliveryService.getDevLatestOtp(email2,'REGISTER')!;assert.ok(fresh);assert.equal((await axios.post(`${base}/api/auth/register/verify-otp`,{email:email2,otp:fresh})).status,200)});
console.log(`\nAuthentication self-check passed (${checks.length}/${checks.length} checks).`)}finally{await User.deleteMany({email:{$in:[email,email2]}});await OtpVerification.deleteMany({email:{$in:[email,email2]}});await new Promise<void>(resolve=>server.close(()=>resolve()));rateLimiterStore.destroy();await mongoose.disconnect()}}
main().catch(error=>{console.error(`Authentication self-check failed: ${error instanceof Error?error.stack:error}`);process.exit(1)});
