import { Request, Response, Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import User, { UserDocument } from '../models/User';
import authenticateToken from '../middleware/auth';
import requireRole from '../middleware/role';
import { authRateLimiter } from '../middleware/rate-limiter';
import { auditService } from '../audit/audit.service';
interface RegisterBody{name?:unknown;email?:unknown;password?:unknown;dateOfBirth?:unknown;phone?:unknown;registrationNumber?:unknown} interface LoginBody{email?:unknown;password?:unknown}
const router=Router(),emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,phonePattern=/^\+?[0-9][0-9\s-]{6,19}$/;
function safeUser(user:UserDocument){return{id:user._id.toString(),name:user.name,email:user.email,role:user.role,isVerified:user.isVerified,...(user.dateOfBirth&&{dateOfBirth:user.dateOfBirth}),...(user.phone&&{phone:user.phone}),...(user.registrationNumber&&{registrationNumber:user.registrationNumber})}}
function issueToken(user:UserDocument){const secret=process.env.JWT_SECRET;if(!secret)throw new Error('JWT secret is not configured');return jwt.sign({id:user._id.toString(),name:user.name,email:user.email,role:user.role},secret,{expiresIn:'1h'})}
function isDuplicate(error:unknown):error is{code:number}{return typeof error==='object'&&error!==null&&'code'in error&&(error as{code:unknown}).code===11000}
router.post('/register',authRateLimiter,async(req:Request<{},{},RegisterBody>,res:Response)=>{const{name,email,password,dateOfBirth,phone,registrationNumber}=req.body;if(typeof name!=='string'||!name.trim()||typeof email!=='string'||!emailPattern.test(email)||typeof password!=='string'||password.length<8)return res.status(400).json({message:'Name, valid email, and password of at least 8 characters are required'});if(dateOfBirth!==undefined&&(typeof dateOfBirth!=='string'||Number.isNaN(new Date(dateOfBirth).getTime())))return res.status(400).json({message:'dateOfBirth must be a valid date string'});if(phone!==undefined&&(typeof phone!=='string'||!phonePattern.test(phone.trim())))return res.status(400).json({message:'phone must be a valid phone number'});if(registrationNumber!==undefined&&(typeof registrationNumber!=='string'||!registrationNumber.trim()))return res.status(400).json({message:'registrationNumber must be a non-empty string'});try{const normalized=email.toLowerCase().trim();if(await User.exists({email:normalized}))return res.status(409).json({message:'Email is already registered'});const user=await User.create({name:name.trim(),email:normalized,password:await bcrypt.hash(password,10),role:'citizen',isVerified:true,...(dateOfBirth&&{dateOfBirth:dateOfBirth.trim()}),...(phone&&{phone:phone.trim()}),...(registrationNumber&&{registrationNumber:registrationNumber.trim()})});const token=issueToken(user);await auditService.record({actorId:user.id,actorRole:user.role,action:'USER_REGISTERED',resource:'user',resourceId:user.id,requestId:req.requestId,outcome:'SUCCESS',metadata:{email:normalized,role:user.role}});return res.status(201).json({message:'Registration successful',token,user:safeUser(user)})}catch(error){if(isDuplicate(error))return res.status(409).json({message:'Email is already registered'});await auditService.record({actorId:null,action:'USER_REGISTERED',resource:'user',requestId:req.requestId,outcome:'FAILURE',metadata:{reason:'internal_error'}});return res.status(500).json({message:'Registration failed'})}});
router.post('/login',authRateLimiter,async(req:Request<{},{},LoginBody>,res:Response)=>{const{email,password}=req.body;if(typeof email!=='string'||typeof password!=='string')return res.status(400).json({message:'Email and password are required'});try{const user=await User.findOne({email:email.toLowerCase().trim()}).select('+password');const valid=user&&await bcrypt.compare(password,user.password);if(!valid){await auditService.record({actorId:user?._id.toString()??null,...(user&&{actorRole:user.role,resourceId:user._id.toString()}),action:'USER_LOGIN',resource:'user',requestId:req.requestId,outcome:'FAILURE',metadata:{reason:'invalid_credentials'}});return res.status(401).json({message:'Invalid email or password'})}if(!user.isVerified)return res.status(403).json({message:'Account is disabled'});const token=issueToken(user);await auditService.record({actorId:user.id,actorRole:user.role,action:'USER_LOGIN',resource:'user',resourceId:user.id,requestId:req.requestId,outcome:'SUCCESS'});return res.json({message:'Login successful',token,user:safeUser(user)})}catch{return res.status(500).json({message:'Login failed'})}});
router.get('/me',authenticateToken,(req,res)=>res.json({user:req.user}));router.get('/test-admin',authenticateToken,requireRole('admin'),(_req,res)=>res.json({message:'Admin access granted'}));router.get('/test-officer',authenticateToken,requireRole('admin','department_officer'),(_req,res)=>res.json({message:'Officer/Admin access granted'}));router.get('/test-citizen',authenticateToken,requireRole('citizen'),(_req,res)=>res.json({message:'Citizen access granted'}));
export default router;
